[project]
name = "improving-planning-with-ull"
version = "1.0.0"
description = "A project consisting of example code, demonstrating Portia AI's user-led learning feature."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["dotenv>=0.9.9", "portia-sdk-python>=0.7.0,<0.8.0"]
