[project]
name = "simple-planning-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "portia-sdk-python[google,mistralai,ollama] (>=0.7.0,<0.8.0)",
]
